"use client";
import {useEffect,useRef,useState} from "react";
import {Activity,ArrowUpRight,Check,ChevronRight,Code2,Download,GitBranch,Loader2,Play,RotateCcw,Search,Share2,Sparkles,WifiOff,X,Zap} from "lucide-react";
import {Tabs,TabsList,TabsTrigger} from "@/components/ui/tabs";
import {Dialog,DialogContent,DialogDescription,DialogTitle} from "@/components/ui/dialog";
type Stage="ready"|"loading"|"results"|"broken"|"generating"|"recovered";
type Scenario="search"|"upload"|"checkout";
const stories={search:{name:"Search timeout",app:"roam",query:"Weekend in Kyoto",event:"GET /stays/search",recovery:"Your next trip can wait a second.",detail:"We couldn't reach the server. Your search is saved. Give it another try.",retry:"Try search again",flow:"Search",success:"Stays found"},upload:{name:"Upload interrupted",app:"folio",query:"Brand explorations.fig",event:"POST /files/upload",recovery:"Your work is still here.",detail:"The connection dropped. Your file is selected and ready for another attempt.",retry:"Try upload again",flow:"Upload",success:"Upload complete"},checkout:{name:"Checkout failure",app:"form",query:"Everyday essentials",event:"GET /orders/status",recovery:"Let's check before you try again.",detail:"We couldn't confirm your order. Check its status before making another payment.",retry:"Check order status",flow:"Checkout",success:"Order status found"}};
const measure="https://measure.sh/?utm_source=measure_flow&utm_medium=interactive_demo&utm_campaign=break_the_happy_path";
export default function Home(){
 const [scenario,setScenario]=useState<Scenario>("search"),[stage,setStage]=useState<Stage>("ready"),[compare,setCompare]=useState(false),[modal,setModal]=useState<"share"|"stitch"|null>(null),[notice,setNotice]=useState(""),[live,setLive]=useState(false),[image,setImage]=useState(""),[busy,setBusy]=useState(false),[tour,setTour]=useState(false),[tourTime,setTourTime]=useState(0);
 const [designing,setDesigning]=useState(false),[designReady,setDesignReady]=useState(false),[designStyle,setDesignStyle]=useState("calm");
 const timers=useRef<ReturnType<typeof setTimeout>[]>([]),generation=useRef(0);const d=stories[scenario],broken=["broken","generating"].includes(stage),recovered=stage==="recovered";
 const clear=()=>{timers.current.forEach(clearTimeout);timers.current=[];};const later=(fn:()=>void,ms:number)=>timers.current.push(setTimeout(fn,ms));
 const reset=()=>{clear();setDesigning(false);setDesignReady(false);generation.current++;setStage("ready");setCompare(false);setTour(false);setTourTime(0);setBusy(false);setImage("");};
 const play=()=>{clear();setDesigning(false);setTour(false);setStage("loading");setCompare(false);later(()=>setStage("results"),1500);};
 const breakFlow=()=>{clear();setDesigning(false);setTour(false);setStage("broken");setCompare(false);};
 const choose=(s:Scenario)=>{reset();setScenario(s);};const notify=(s:string)=>{setNotice(s);setTimeout(()=>setNotice(""),4500);};
 const prepared=()=>{generation.current++;setBusy(false);setImage("");setStage("recovered");setCompare(true);setModal(null);};
 const runTour=()=>{reset();setScenario("search");setTour(true);later(()=>setStage("loading"),2000);later(()=>setStage("results"),3500);later(()=>setStage("broken"),5500);later(()=>setStage("generating"),8500);later(()=>{setStage("recovered");setCompare(true);},12000);later(()=>setCompare(false),16000);later(()=>setTour(false),20000);};
 useEffect(()=>{fetch("/api/stitch").then(r=>r.json()).then((v:unknown)=>setLive(Boolean((v as {configured?:boolean}).configured))).catch(()=>{});return clear;},[]);
 useEffect(()=>{if(!tour)return;const t=setInterval(()=>setTourTime(v=>Math.min(20,v+.1)),100);return()=>clearInterval(t);},[tour]);
 useEffect(()=>{const api={setStage:(v:Stage)=>{clear();setStage(v);setCompare(v==="recovered");},setScenario:choose,runTour};(window as any).measureDemo=api;const ctx=(document as any).modelContext,abort=new AbortController();if(ctx?.registerTool){try{Promise.resolve(ctx.registerTool({name:"set_demo_state",description:"Show a simulated flow state. Does not generate a design or alter a real app.",inputSchema:{type:"object",properties:{state:{type:"string",enum:["ready","broken","recovered"]}},required:["state"],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(v:any)=>{if(!["ready","broken","recovered"].includes(v.state))throw new Error("Invalid demo state");api.setStage(v.state);return{state:v.state,simulation:true};}},{signal:abort.signal})).catch(()=>{});}catch{}}return()=>abort.abort();},[scenario]);
 async function generate(){clear();setDesigning(false);setTour(false);setBusy(true);setStage("generating");const id=++generation.current;try{if(!live){await new Promise(r=>setTimeout(r,1300));if(id!==generation.current)return;setStage("recovered");setCompare(true);notify("Prepared example. No live Stitch call was made.");return;}const r=await fetch("/api/stitch",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({scenario})}),v=await r.json() as {error?:string;image:string};if(id!==generation.current)return;if(!r.ok)throw new Error(v.error||"Generation unavailable");setImage(v.image);setStage("recovered");setCompare(true);notify("Live Stitch design received.");}catch(e){if(id===generation.current){setStage("broken");notify(e instanceof Error?e.message:"Generation failed");}}finally{if(id===generation.current)setBusy(false);}}
 async function share(){try{await navigator.clipboard.writeText(`Explore the Stitch-to-Measure workflow: design a screen, break its happy path, and design a way back. Try Measure Flow.\n${location.origin}`);notify("Link copied. Site sharing permissions still apply.");}catch{notify("Copy the demo URL from your browser.");}}
 function download(){const c=document.createElement("canvas");c.width=1600;c.height=900;const x=c.getContext("2d")!;x.fillStyle="#101014";x.fillRect(0,0,1600,900);x.fillStyle="#c2ff62";x.font="bold 28px Arial";x.fillText("STITCH WORKFLOW / MEASURE FLOW LAB",80,80);x.fillStyle="#fff";x.font="bold 72px Arial";x.fillText("I broke the happy path.",80,200);x.fillStyle="#b8a3ff";x.fillText("Then designed a way back.",80,285);[{p:80,title:"BEFORE",color:"#ff98a6",lines:[d.flow,"Request fails","No clear next step"]},{p:825,title:"PROPOSED AFTER",color:"#c2ff62",lines:[d.flow,"Clear recovery state","Explicit next action"]}].forEach(b=>{x.fillStyle="#211c29";x.beginPath();x.roundRect(b.p,350,690,320,24);x.fill();x.fillStyle=b.color;x.font="bold 22px Arial";x.fillText(b.title,b.p+35,400);x.fillStyle="#fff";x.font="32px Arial";b.lines.forEach((v,i)=>x.fillText(`${i+1}. ${v}`,b.p+35,465+i*65));});x.font="24px Arial";x.fillStyle="#bbb";x.fillText(image?"Simulated journey · Live Stitch design in demo":"Simulated journey · Prepared recovery example",80,740);x.fillStyle="#c2ff62";x.font="bold 36px Arial";x.fillText("See your real app with measure.sh",80,825);const a=document.createElement("a");a.download="measure-flow-before-after.png";a.href=c.toDataURL();a.click();}
 const createScreen=()=>{clear();setTour(false);setCompare(false);setImage("");setDesignReady(false);setDesigning(true);setStage("loading");later(()=>{setDesigning(false);setDesignReady(true);setStage("ready");},1400);};
 const designPrompt=`Design a mobile ${d.flow.toLowerCase()} screen for ${d.app}. ${designStyle==="calm"?"Use warm neutrals, olive buttons, and quiet editorial typography.":"Use a violet accent, crisp typography, and a confident primary action."} Preserve the user's input. Include a clear next step.`;
 const step=recovered?3:broken?2:stage==="loading"?1:stage==="results"?3:0;
 return <main className={designStyle==="bold"?"bold-design":""}><nav className="topbar"><a className="brand" href={measure} target="_blank" rel="noreferrer"><Activity size={26}/>measure<span className="slash">/</span><span className="lab">FLOW LAB</span></a><div className="navright"><button className="textbutton" onClick={()=>setModal("stitch")}><Sparkles size={15}/>{live?"Stitch connected":"Stitch integration"}</button><a href={measure} target="_blank" rel="noreferrer">Explore Measure <ArrowUpRight size={16}/></a></div></nav>
 <section className="intro"><div><div className="eyebrow">STITCH × MEASURE / AN INTERACTIVE CONCEPT</div><h1>Design it with Stitch.<br/><span>See it through Measure.</span></h1><p>From a design prompt to a broken flow to a better way back.<br className="desktop"/> Explore the Stitch workflow. Discover why your app needs Measure.</p></div><button className="watch" onClick={runTour}><span className="playcircle"><Play size={17} fill="currentColor"/></span><span>Watch the story<small>A quick interactive walkthrough.</small></span></button></section>
 <section className="integration-story" aria-label="Stitch and Measure workflow"><button onClick={createScreen} disabled={busy}><span className="story-icon stitch-icon"><Sparkles size={20}/></span><span><small>01 / STITCH</small><strong>Prompt to screen</strong></span></button><ChevronRight className="story-arrow"/><button onClick={breakFlow} disabled={busy}><span className="story-icon measure-icon"><Activity size={20}/></span><span><small>02 / MEASURE</small><strong>Reveal the failure</strong></span></button><ChevronRight className="story-arrow"/><button onClick={generate} disabled={busy}><span className="story-icon stitch-icon"><Sparkles size={20}/></span><span><small>03 / STITCH</small><strong>Design a way back</strong></span></button><div className="story-mode">{live?"Live recovery available":"FRONTEND WORKFLOW DEMO"}<small>Sample screens · simulated telemetry</small></div></section>
 <section className="workspace" aria-label="Interactive flow demo"><div className="toolbar"><div className="project"><GitBranch size={16}/><strong>The happy path</strong><span className="badge">SIMULATED APP</span></div><Tabs value={scenario} onValueChange={v=>choose(v as Scenario)}><TabsList className="scenario-tabs">{Object.entries(stories).map(([key,v])=><TabsTrigger key={key} value={key}>{v.name}</TabsTrigger>)}</TabsList></Tabs><button className="iconbutton" aria-label="Reset demo" onClick={reset}><RotateCcw size={16}/></button></div>
 <div className="stagegrid"><aside className="journey stitch-composer"><div className="stitch-heading"><span className="stitch-icon"><Sparkles size={24}/></span><div><strong>Stitch</strong><small>THE DESIGN WORKSPACE</small></div><span className="demo-chip">DEMO</span></div><p className="composer-intro">An idea becomes a screen.<br/>Then reality becomes the next prompt.</p><label className="prompt-label" htmlFor="stitch-prompt">YOUR DESIGN BRIEF</label><textarea id="stitch-prompt" value={designPrompt} readOnly aria-label="Stitch design brief"/><Tabs value={designStyle} onValueChange={v=>{setDesignStyle(v);setDesignReady(false);}}><TabsList className="design-tabs"><TabsTrigger value="calm">Calm editorial</TabsTrigger><TabsTrigger value="bold">Bold violet</TabsTrigger></TabsList></Tabs><button className="stitch-create" onClick={createScreen} disabled={busy||designing}>{designing?<Loader2 size={16} className="spin"/>:<Sparkles size={16}/>} {designing?"Preparing screen…":"Create screen · demo"}</button><div className="design-status" role="status">{designing?"Simulating the prompt-to-screen step":designReady?"Sample screen ready. Now test its happy path.":"Prepared screens, not live generated output."}</div><div className="recovery-brief"><span><Activity size={14}/> CONTEXT FROM MEASURE</span><p>{broken||recovered?`${d.event} timed out in this simulated session. Keep the input and make recovery explicit.`:"Break the flow to turn a failure into the next design brief."}</p></div><button className="stitch-recover" disabled={busy} onClick={generate}><Sparkles size={15}/>{busy?"Preparing recovery…":live?"Generate recovery with Stitch":"Stitch recovery · demo"}</button><small className="composer-disclosure">{live?"Recovery uses your connected Stitch account.":"Frontend preview. Live recovery uses the included Stitch MCP adapter when connected."}</small></aside>
 <div className="phonesurface"><div className="surfaceheader"><span>{recovered?"STITCH / RECOVERY DESIGN":"STITCH / SCREEN CANVAS"}</span><span>{compare?"BEFORE / PROPOSED AFTER":"MOBILE PREVIEW"}</span></div><div className={`phones ${compare?"comparing":""}`}>{compare&&<div className="phonewrap"><span className="phonelabel beforelabel">BEFORE</span><Phone d={d} state="broken"/></div>}<div className="phonewrap"><span className={`phonelabel ${recovered?"afterlabel":""}`}>{recovered?"PROPOSED AFTER":stage==="generating"?"STITCH RECOVERY WORKFLOW":designing?"PROMPT TO SCREEN · DEMO":`${d.app.toUpperCase()} / PREPARED SCREEN`}</span><Phone d={d} state={stage} image={image} retry={play}/></div></div><div className="previewcaption">{stage==="generating"?<><Loader2 className="spin" size={13}/>{live&&!tour?"Requesting a design from Stitch…":"Loading the prepared recovery example…"}</>:recovered?<><Sparkles size={13}/>{image?"Live Stitch design · simulated behavior":"Stitch workflow demo · prepared recovery"}</>:<><span className="keycap">DEMO</span>Click a flow step to explore the screen</>}</div></div>
 <aside className="inspector"><div className="sectionlabel">MEASURE / FAILURE CONTEXT<Code2 size={14}/></div><div className="inspectorheading"><Activity size={20}/><div><strong>{broken?"A request went missing.":recovered?"Recovery has a design.":"Follow the evidence."}</strong><small>Measure-inspired demo timeline</small></div></div><div className="events">{["Screen opened","Action tapped",broken?"Request timed out":recovered?"Recovery proposed":"Awaiting response"].map((e,i)=><div key={i} className={broken&&i===2?"eventerror":""}><span className="eventdot"/><code>{["00:00.000","00:00.240","00:08.240"][i]}</code><strong>{e}</strong><small>{i===2?d.event:i===0?`${d.flow.toLowerCase()}.screen_view`:`${d.flow} button`}</small></div>)}</div><div className="insight"><span className="eyebrow">THE MISSING PIECE</span><h3>{recovered?"A design is a hypothesis.":"Your UI can't tell you everything."}</h3><p>{recovered?"See how people actually experience your app. Measure brings the real context.":"Measure connects errors, sessions, and performance so you can investigate what happened."}</p><a href={measure} target="_blank" rel="noreferrer">See Measure in action <ArrowUpRight size={14}/></a></div></aside></div>
 <div className="flow-ribbon" aria-label="Visual app flow"><span>APP JOURNEY</span>{[d.flow,"Request",broken?"Timeout":recovered?"Recovery":"Response",recovered?"Try again":broken?"Dead end":d.success].map((label,i)=><span className={`flow-step ${i===step?"selected":""}`} key={i}>{i>0&&<ChevronRight size={13}/>}<span>{label}</span></span>)}</div><div className="controlbar"><div className="controlnote"><span className={`statepill ${broken?"bad":recovered?"good":""}`}>{recovered?"RECOVERY":broken?"FAILURE":"HAPPY PATH"}</span><span>{recovered?"A better next step. Ready to share?":"Go on. See what breaks."}</span></div><div className="actions"><button className="secondary" onClick={play} disabled={busy}><Play size={15}/>Play flow</button><button className="danger" onClick={breakFlow} disabled={busy}><Zap size={15}/>Break the flow</button>{recovered?<button className="primary" onClick={()=>setModal("share")}><Share2 size={15}/>Share the story</button>:<button className="primary" disabled={busy} onClick={generate}>{busy?<Loader2 size={15} className="spin"/>:<Sparkles size={15}/>} {live?"Design with Stitch":"Stitch recovery · demo"}</button>}</div></div></section>
 <section className="bottomline"><div><span className="bracket">[</span><p>Stitch designs the possibility.<br/><strong>Measure shows you the reality.</strong></p></div><a href={measure} target="_blank" rel="noreferrer">Monitor your real app <ArrowUpRight size={17}/></a><span className="disclaimer">Concept demo · No real user data<br/>No automatic fixes or deployment</span></section><footer><span>MEASURE FLOW LAB / 2026</span><span>Built for the moments between “it works” and “it works for everyone.”</span></footer>
 {tour&&<div className="tourbar"><span><Play size={13}/>GUIDED STORY · PREPARED DEMO</span><div><i style={{width:`${tourTime/20*100}%`}}/></div><button aria-label="Stop walkthrough" onClick={()=>{clear();setTour(false);}}><X size={16}/></button></div>}{notice&&<div role="status" className="toast">{notice}</div>}
 <Dialog open={!!modal} onOpenChange={v=>{if(!v)setModal(null);}}><DialogContent className="flowdialog"><DialogTitle>{modal==="share"?"A story worth sharing.":"Stitch, inside the flow."}</DialogTitle><DialogDescription>{modal==="share"?"Share the proposed recovery, not a promise of a fix.":"Design generation connects through a server-side Stitch SDK / MCP adapter."}</DialogDescription>{modal==="share"?<><div className="sharepreview"><span>STITCH WORKFLOW / MEASURE FLOW LAB</span><h2>I broke the happy path.<br/><em>Then designed a way back.</em></h2><div><span>Timeout<br/><b>No clear next step</b></span><ChevronRight/><span>Recovery<br/><b>Try again, with context</b></span></div><small>{image?"Live Stitch design":"Prepared recovery example"} · Simulated journey</small></div><button className="primary" onClick={download}><Download size={16}/>Download share image</button><button className="secondary" onClick={share}><Share2 size={16}/>Copy demo link</button></>:<><div className="integrationpath"><span>Measure brief</span><ChevronRight/><span>Stitch MCP</span><ChevronRight/><span>Recovery design</span></div><div className="connection"><span>{live?"CONNECTED":"PREPARED DEMO MODE"}</span><p>{live?"Live requests use server-side Stitch credentials.":"No Stitch key is configured. This visual demo uses a labeled prepared recovery. The backend adapter is included for live generation."}</p></div><button className="primary" onClick={prepared}>Explore prepared recovery</button></>}</DialogContent></Dialog>
 </main>;
}
function Phone({d,state,image="",retry}:{d:typeof stories.search,state:Stage,image?:string,retry?:()=>void}){const failed=["broken","generating"].includes(state),recovered=state==="recovered";return <div className="phone"><div className="phone-status"><span>9:41</span><span className="island"/><span>▮▮▮ ▰</span></div><div className="phone-body"><div className="appbrand">{d.app}<span>✳</span></div><div className="appintro"><small>MAKE ROOM FOR SOMETHING GOOD</small><h3>{d.app==="roam"?"Find your\nnext escape.":d.app==="folio"?"Good work.\nAll together.":"Everyday,\na little better."}</h3></div><div className="searchbox"><Search size={12}/>{d.query}</div>{recovered&&image?<div className="generatedpreview"><img src={image} alt="Recovery screen generated by Stitch"/></div>:failed?<div className="errorcard"><span className="erroricon"><WifiOff size={24}/></span><h4>Something went wrong.</h4><p>Error 408. Please try later.</p><div className="deadbutton">OK</div></div>:recovered?<div className="recoverycard"><span className="recoveryicon"><WifiOff size={16}/></span><h4>{d.recovery}</h4><p>{d.detail}</p><button onClick={retry}>{d.retry}</button><small><Check size={10}/>Your progress is preserved</small></div>:state==="loading"?<div className="loadingphone"><Loader2 size={28} className="spin"/><strong>Finding the good stuff…</strong><div className="skeletonline"/><div className="skeletonline short"/></div>:<div className="appresults">{state==="results"&&<div className="found"><Check size={12}/>{d.success} · demo</div>}<div className="staycard"><div className="staytop"><span>01</span><span>CURATED COLLECTION</span></div><h4>{d.app==="roam"?"Somewhere\nslower.":d.app==="folio"?"Your ideas,\nin one place.":"Less, but\nbetter."}</h4><div className="staybottom"><span>{d.app==="roam"?"KYOTO, JAPAN":"MADE FOR EVERY DAY"}</span><ArrowUpRight size={15}/></div></div><div className="listing">{d.app==="roam"?"A little closer to nature":"A thoughtful place to start"}<small>Made for you</small></div></div>}<div className="phone-nav"><span>Explore</span><span>Saved</span><span>Profile</span></div></div><div className="homeindicator"/></div>}

